export enum UserRole {
    ADMIN = 'ADMIN',
    ASSOCIATION = 'ASSOCIATION',
    USER = 'USER',
}

export enum ProjectStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    FUNDRAISING = 'FUNDRAISING',
    COMPLETED = 'COMPLETED',
    REJECTED = 'REJECTED',
}

export enum BadgeTier {
    BRONZE = 'BRONZE',
    SILVER = 'SILVER',
    GOLD = 'GOLD',
    DIAMOND = 'DIAMOND',
}

export enum PrivilegeType {
    VOTE_ON_PROPOSALS = 'VOTE_ON_PROPOSALS',
    EARLY_ACCESS_PROJECTS = 'EARLY_ACCESS_PROJECTS',
    CREATE_PROPOSALS = 'CREATE_PROPOSALS',
    PARTICIPATE_GOVERNANCE = 'PARTICIPATE_GOVERNANCE',
    REDUCED_FEES = 'REDUCED_FEES',
    PRIORITY_SUPPORT = 'PRIORITY_SUPPORT',
}
